# create an Azure Pipeline that runs only manually.  The pipeline
# should require the following input parameters:
# - ApiManagementName: The name of the APIM instance to restore
# - ApiManagementResourceGroup: The resource group containing the APIM instance
# - StorageAccountName: The name of the storage account to restore the backup from
# - StorageResourceGroup: The resource group containing the storage account
# - ContainerName: The name of the storage container to restore the backup from
# - BackupFileName: The name of the backup to restore
# - ServiceConnectionName

# All parameters are of type string and should be mandatory.  The pipeline
# will have a single stage and sinlge job that run on the Microsoft Hosted
# Ubuntu 22.04 agent.  The pipeline job should use the Azure Powershell task
# to execute the Powershell script Restore-Api-Management.ps1 located in the
# path $(System.DefaultWorkingDirectory)/.pipelines/scripts/Restore-Api-Management.ps1.
# The Azure Powershell task should be configured to use the Service Connection
# provided in the parameter ServiceConnectionName.
parameters:
- name: DeployInfrastructure
  type: boolean
  default: false
- name: ApiManagementName
  type: string
- name: ApiManagementResourceGroup
  type: string
- name: StorageAccountName
  type: string
- name: StorageResourceGroup
  type: string
- name: ContainerName
  type: string
- name: BackupFileName
  type: string
- name: Location
  type: string
- name: SkuName
  type: string
  values:
  - Developer
  - Basic
  - Standard
  - Premium
- name: SkuCapacity
  type: number
  default: 1
- name: PublisherEmailAddress
  type: string
- name: PublisherName
  type: string
- name: VnetIntegrationMode
  type: string
  values:
  - None
  - External
  - Internal
- name: vnetSubnetResourceId
  type: string
- name: publicIpResourceId
  type: string
- name: ServiceConnectionName
  type: string

trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  infraTemplate: '$(System.DefaultWorkingDirectory)/.infrastructure/bicep/main.bicep'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy API Management Resource
  condition: eq('${{ parameters.DeployInfrastructure }}', true)
  inputs:
    deploymentScope: Resource Group
    azureResourceManagerConnection: ${{ parameters.ServiceConnectionName }}
    resourceGroupName: ${{ parameters.ApiManagementResourceGroup }}
    csmFile: $(infraTemplate)
    deploymentName: $(Build.BuildId)
    overrideParameters: '-buildId $(Build.BuildId) -apiManagementServiceName ${{ parameters.ApiManagementName }} -apiManagementResourceGroup ${{ parameters.ApiManagementResourceGroup }} -location ${{ parameters.Location }} -skuName ${{ parameters.SkuName }} -skuCapacity ${{ parameters.SkuCapacity }} -publisherEmailAddress ${{ parameters.PublisherEmailAddress }} -publisherName ${{ parameters.PublisherName }} -vnetIntegrationMode ${{ parameters.VnetIntegrationMode }} -vnetSubnetResourceId ${{ parameters.vnetSubnetResourceId }} -publicIpResourceId ${{ parameters.publicIpResourceId }}'
    location: ${{ parameters.Location }}

- task: AzurePowerShell@5
  displayName: 'Restore APIM'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnectionName }}
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)/.pipelines/scripts/Restore-Api-Management.ps1'
    ScriptArguments: '-ApiManagementName $(ApiManagementName) -ApiManagementResourceGroup $(ApiManagementResourceGroup) -StorageAccountName $(StorageAccountName) -StorageResourceGroup $(StorageResourceGroup) -ContainerName $(ContainerName) -BackupFileName $(BackupFileName)'
    azurePowerShellVersion: 'LatestVersion'